views:
  template_extension: "hgo"
  dir: "apps_web/templates"
  layout: "layouts/master"
repo:
  host: "127.0.0.1"
  user: "postgres"
  password: "postgres"
  dbname: "mila"
  port: "5432"
  sslmode: "disable"
  TimeZone: "Asia/Ho_Chi_Minh"